apiVersion: v2
name: kube-dump
description: A Helm chart for kube-dump
type: application
version: "0.2.2" # set by GHA at Mon Nov 10 03:52:06 UTC 2025
appVersion: "0.2.2" # set by GHA at Mon Nov 10 03:52:06 UTC 2025
