apiVersion: v2
name: kube-dump
description: A Helm chart for kube-dump
type: application
version: "0.2.2" # set by GHA at Tue Nov  4 03:43:22 UTC 2025
appVersion: "0.2.2" # set by GHA at Tue Nov  4 03:43:22 UTC 2025
