apiVersion: v2
name: kube-dump
description: A Helm chart for kube-dump
type: application
version: "0.2.2" # set by GHA at Fri Nov 14 03:47:02 UTC 2025
appVersion: "0.2.2" # set by GHA at Fri Nov 14 03:47:02 UTC 2025
