apiVersion: v2
name: kube-dump
description: A Helm chart for kube-dump
type: application
version: "0.2.2" # set by GHA at Sun Nov 16 03:50:51 UTC 2025
appVersion: "0.2.2" # set by GHA at Sun Nov 16 03:50:51 UTC 2025
